### PR TITLE
BetterOptional

### PR DESCRIPTION
**Pull request by Y2Kwastaken**
Goals
- Provide a clear and decisive use for BetterBoolean
- Enable BetterBoolean to work within an Optional as expected

### CODE REVIEW

**Review by Y2Kwastaken — COMMENTED** [review]
lgtm

**Comment by Reecepbcups** [comment]
lgtm

**Comment by OkKloon** [comment]
lgtm 😊

**Comment by mfnalex** [comment]
Dude you fucking violated the code of conduct. You should not have written a proper pull request description. I will merge this anyway ,thank you so much for this "very useful contribution"

**Pull request merged**
